name: dml-store

services:
  # ==========================================
  # [PROFILE: clickhouse] Real-Time OLAP
  # ==========================================
  clickhouse:
    image: clickhouse/clickhouse-server:26.3-alpine
    container_name: clickhouse
    restart: on-failure
    profiles:
      - clickhouse
    networks:
      - dml
    ports:
      - "8123:8123" # HTTP API
      - "9000:9000" # Native TCP
    mem_limit: 4g
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8123/ping",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  # [PROFILE: fluss] Streaming Storage Engine
  # ==========================================
  zookeeper:
    image: zookeeper:3.9.2
    container_name: zookeeper
    profiles:
      - fluss
    networks:
      - dml
    ports:
      - "2181:2181"
    mem_limit: 1g
    environment:
      - JVM_ARGS=-Xmx512m
    restart: always

  fluss-coordinator:
    image: apache/fluss:0.9.0-incubating
    container_name: fluss-coordinator
    command: coordinatorServer
    profiles:
      - fluss
    ports:
      - "9123:9123"
    networks:
      - dml
    depends_on:
      - zookeeper
    environment:
      - |
        FLUSS_PROPERTIES=
        zookeeper.address: zookeeper:2181
        bind.listeners: INTERNAL://fluss-coordinator:0, CLIENT://fluss-coordinator:9123
        # Use container name so Flink inside the 'dml' network can resolve it
        advertised.listeners: CLIENT://fluss-coordinator:9123
        internal.listener.name: INTERNAL
        remote.data.dir: /tmp/fluss/remote-data

  fluss-tablet:
    image: apache/fluss:0.9.0-incubating
    container_name: fluss-tablet
    command: tabletServer
    profiles:
      - fluss
    ports:
      - "9124:9123"
    networks:
      - dml
    depends_on:
      - fluss-coordinator
    mem_limit: 2g
    environment:
      - JVM_ARGS=-Xmx1500m
      - |
        FLUSS_PROPERTIES=
        zookeeper.address: zookeeper:2181
        bind.listeners: INTERNAL://fluss-tablet:0, CLIENT://fluss-tablet:9123
        # Use container name so Flink inside the 'dml' network can resolve it
        advertised.listeners: CLIENT://fluss-tablet:9123
        internal.listener.name: INTERNAL
        tablet-server.id: 0
        kv.snapshot.interval: 0s
        data.dir: /tmp/fluss/data
        remote.data.dir: /tmp/fluss/remote-data

networks:
  dml:
    name: dml
    external: true
