name: dml-mlops

services:
  # ==========================================
  # [PROFILE: mlflow] Experiment Tracking
  # ==========================================
  mlflow:
    image: ghcr.io/jaehyeon-kim/open-dataml-stack/mlflow:${TAG:-latest}
    container_name: mlflow
    profiles:
      - mlflow
    networks:
      - dml
    ports:
      - "5000:5000"
    mem_limit: 1g
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-user}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-password}
      AWS_DEFAULT_REGION: us-east-1
      MLFLOW_S3_ENDPOINT_URL: http://seaweed:8333
      # For quick experiments
      _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
    command: >
      mlflow server
      --backend-store-uri postgresql+psycopg2://${POSTGRES_USER:-user}:${POSTGRES_PASSWORD:-password}@postgres/mlflow
      --artifacts-destination s3://warehouse/mlflow
      --serve-artifacts
      --host 0.0.0.0
      --port 5000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ==========================================
  # [PROFILE: feast] Feature Store
  # ==========================================
  feast:
    image: ghcr.io/jaehyeon-kim/open-dataml-stack/feast:${TAG:-latest}
    container_name: feast
    profiles:
      - feast
    networks:
      - dml
    ports:
      - "6566:6566"
    mem_limit: 1g
    volumes:
      - ./feast:/opt/feast/feature_repo
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-user}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-password}
      AWS_DEFAULT_REGION: us-east-1
      FEAST_S3_ENDPOINT_URL: http://seaweed:8333
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      VALKEY_USER: ${VALKEY_USER:-user}
      VALKEY_PASSWORD: ${VALKEY_PASSWORD:-password}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-user}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password}
      # For quick experiments
      _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
    command: >
      bash -c "
      echo 'Waiting for infrastructure (Postgres, Valkey, ClickHouse) to be available...'
      while ! timeout 1 bash -c '</dev/tcp/postgres/5432'; do sleep 2; done
      while ! timeout 1 bash -c '</dev/tcp/valkey/6379'; do sleep 2; done
      while ! timeout 1 bash -c '</dev/tcp/clickhouse/8123'; do sleep 2; done

      echo 'Infrastructure is up! Applying Feast metadata...'
      cd /opt/feast/feature_repo
      feast apply

      echo 'Starting Feast Server...'
      feast serve -h 0.0.0.0 -p 6566
      "

networks:
  dml:
    name: dml
    external: true
