import os
import shutil
from typing import Optional
from importlib.metadata import PackageNotFoundError, version

from odctl.config import INTERNAL_RESOURCES_DIR, get_workspace_dir


def get_cli_version() -> str:
    """
    Retrieve the version of the installed odctl package.

    Returns:
        str: The installed package version, or 'latest' if run directly from source
        without installation.
    """
    try:
        # This string must exactly match the 'name' in your pyproject.toml
        return version("odctl")
    except PackageNotFoundError:
        # Fallback for when you are developing locally and haven't installed the package
        return "latest"


def stale_workspace_tag() -> Optional[str]:
    """
    Return the workspace's TAG when it no longer matches this CLI's version.

    `odctl init` writes TAG from the CLI version once, so upgrading the CLI later
    leaves the workspace starting the old images and compose files, with no sign
    of it. A TAG set in the shell is an explicit choice and is not reported.

    Returns:
        Optional[str]: The stale TAG, or None when there is no workspace, no TAG,
        a shell override, or a match.
    """
    if os.environ.get("TAG"):
        return None
    env_file = get_workspace_dir() / ".env"
    if not env_file.exists():
        return None
    for line in env_file.read_text().splitlines():
        key, _, value = line.strip().partition("=")
        if key == "TAG":
            tag = value.strip().strip('"').strip("'")
            cli = get_cli_version()
            return tag if tag and cli != "latest" and tag != cli else None
    return None


def init_workspace(force: bool = False):
    """
    Copy all internal resources to the local user workspace.

    Args:
        force (bool, optional): If True, completely deletes the existing workspace and
                                recreates it from scratch. Defaults to False.
    """
    workspace = get_workspace_dir()

    # Nuke the existing workspace if force is True
    if force and workspace.exists():
        shutil.rmtree(workspace)
        print(f"🗑️  Removed existing workspace at {workspace}/")

    if not workspace.exists():
        workspace.mkdir(parents=True)
        print(f"📁 Created workspace at {workspace}/")

    # Iterate over everything in the internal resources
    for item in INTERNAL_RESOURCES_DIR.iterdir():
        dest = workspace / item.name

        # Only copy if it doesn't exist (or was just deleted by force)
        if not dest.exists():
            if item.is_dir():
                shutil.copytree(item, dest)
            else:
                shutil.copy2(item, dest)
            print(f"  └─ Copied: {item.name}")

    # Generate the .env file dynamically
    cli_version = get_cli_version()
    env_file = workspace / ".env"

    # Only create/overwrite .env if force is True OR it doesn't exist yet
    if force or not env_file.exists():
        with open(env_file, "w") as f:
            f.write(f"# Auto-generated by Open Data Stack CLI v{cli_version}\n")
            f.write(f"TAG={cli_version}\n")
            f.write("TZ=UTC\n\n")

            f.write("# Airflow Additional Dependencies\n")
            f.write('# _AIRFLOW_PIP_DEPS="scikit-learn"\n')
            f.write('_AIRFLOW_PIP_DEPS=""\n\n')

            f.write("# MLOps Additional Dependencies\n")
            f.write('# _MLOPS_PIP_DEPS="pyod river"\n')
            f.write('_MLOPS_PIP_DEPS=""\n\n')

            # Left empty on purpose. The mlflow-serve profile has nothing to
            # serve until a model is logged, so an empty value stops that one
            # container instead of serving something unintended.
            f.write("# MLflow Model Server target: models:/<name>@<alias>,\n")
            f.write("# runs:/<run-id>/<artifact-path>, or an s3:// path\n")
            f.write('# MODEL_URI="models:/my-model@champion"\n')
            f.write('MODEL_URI=""\n\n')

            # ./feast is shipped with the workspace and carries configuration
            # with no feature definitions, so the profile starts before you
            # have written any. Point this at your own repository to use it.
            f.write("# Feast feature repository: a directory holding\n")
            f.write("# feature_store.yaml plus your feature definitions.\n")
            f.write("# Run `feast apply` yourself; odctl ships no definitions.\n")
            f.write('# FEAST_REPO="/path/to/your/feature_repo"\n')
            f.write('FEAST_REPO="./feast"\n')

        print(f"  └─ Generated: .env (TAG={cli_version})")
