name: odctl-spark

x-spark-base: &spark-base
  image: ghcr.io/jaehyeon-kim/odctl/spark:${TAG:-latest}
  networks:
    - odctl
  volumes:
    - odctl-shared-deps:/mnt/shared-deps:ro
    - spark-events-data:/tmp/spark-events
    - ./spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
    - ./spark/log4j2.properties:/opt/spark/conf/log4j2.properties:ro
  environment:
    TZ: ${TZ:-UTC}
    SPARK_DIST_CLASSPATH: "/mnt/shared-deps/shared/*:/mnt/shared-deps/spark/*"

services:
  spark-master:
    <<: *spark-base
    container_name: spark-master
    profiles: ["spark-lite", "spark-full"]
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master
    ports:
      - "9080:8080"
      - "7077:7077"
    mem_limit: 1g
    environment:
      SPARK_WORKER_MEMORY: "1500m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

  spark-worker-1:
    <<: *spark-base
    container_name: spark-worker-1
    profiles: ["spark-lite", "spark-full"]
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    ports:
      - "9081:8081"
    mem_limit: 2g
    environment:
      SPARK_WORKER_MEMORY: "1500m"
    depends_on:
      spark-master:
        condition: service_healthy

  spark-worker-2:
    <<: *spark-base
    container_name: spark-worker-2
    profiles: ["spark-full"]
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    ports:
      - "9082:8081"
    mem_limit: 2g
    environment:
      SPARK_WORKER_MEMORY: "1500m"
    depends_on:
      spark-master:
        condition: service_healthy

  spark-worker-3:
    <<: *spark-base
    container_name: spark-worker-3
    profiles: ["spark-full"]
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    ports:
      - "9083:8081"
    mem_limit: 2g
    environment:
      SPARK_WORKER_MEMORY: "1500m"
    depends_on:
      spark-master:
        condition: service_healthy

  spark-history:
    <<: *spark-base
    container_name: spark-history
    profiles: ["spark-lite", "spark-full"]
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer
    ports:
      - "18080:18080"
    mem_limit: 1g

networks:
  odctl:
    name: odctl
    external: true

volumes:
  odctl-shared-deps:
    name: odctl-shared-deps
    external: true
  spark-events-data:
    name: spark-events-data
