import shutil
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path

from dml.config import INTERNAL_RESOURCES_DIR, get_workspace_dir


def get_cli_version() -> str:
    """Retrieve the version of the installed dml-cli package."""
    try:
        # This string must exactly match the 'name' in your pyproject.toml
        return version("dml-cli")
    except PackageNotFoundError:
        # Fallback for when you are developing locally and haven't installed the package
        return "latest"


def init_workspace(force: bool = False):
    """Copies all internal resources to the local workspace."""
    workspace = get_workspace_dir()

    # Nuke the existing workspace if force is True
    if force and workspace.exists():
        shutil.rmtree(workspace)
        print(f"🗑️  Removed existing workspace at {workspace.relative_to(Path.cwd())}/")

    if not workspace.exists():
        workspace.mkdir(parents=True)
        print(f"📁 Created workspace at {workspace.relative_to(Path.cwd())}/")

    # Iterate over everything in the internal resources
    for item in INTERNAL_RESOURCES_DIR.iterdir():
        dest = workspace / item.name

        # Only copy if it doesn't exist (or was just deleted by force)
        if not dest.exists():
            if item.is_dir():
                shutil.copytree(item, dest)
            else:
                shutil.copy2(item, dest)
            print(f"  └─ Copied: {item.name}")

    # Generate the .env file dynamically
    cli_version = get_cli_version()
    env_file = workspace / ".env"

    # Only create/overwrite .env if force is True OR it doesn't exist yet
    if force or not env_file.exists():
        with open(env_file, "w") as f:
            f.write(f"# Auto-generated by Open DataML Stack CLI v{cli_version}\n")
            f.write(f"TAG={cli_version}\n")
            # Adding TZ=UTC is standard practice for data engineering stacks!
            f.write("TZ=UTC\n")

        print(f"  └─ Generated: .env (TAG={cli_version})")
