name: Build Open Data Dependencies Image

on:
  workflow_call:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/deps


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  validate:
    name: Dry Run Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Script Dry Run
        run: |
          cd src/odctl/resources/deps
          # Make all scripts executable
          chmod +x *.sh

          # Run the Aiven builder dry-run
          ./build_connectors.sh --dry-run

          # Run the standalone plugin and Uber-JAR fetchers dry-runs
          ./fetch_standalone_plugins.sh --dry-run
          ./fetch_flink_dependencies.sh --dry-run
          ./fetch_spark_dependencies.sh --dry-run

  build-and-push:
    name: Build & Push
    needs: validate
    # Still allows the job to run manually so you can test caching, but it won't push unless it's a tag
    if: startsWith(github.ref, 'refs/tags/v') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # Set up Buildx to enable registry caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: src/odctl/resources/deps
          # Strictly enforce push only on 'v' tags
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
