name: Main Pipeline

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-platform:
    uses: ./.github/workflows/build-platform-images.yml
    secrets: inherit

  build-deps:
    uses: ./.github/workflows/build-deps.yml
    secrets: inherit

  e2e:
    needs: [build-platform, build-deps]
    uses: ./.github/workflows/e2e-test.yml
    secrets: inherit
