# Set root logger level to WARN
rootLogger.level = warn
rootLogger.appenderRef.stdout.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n%ex

# Keep Spark's internal web server components a bit quieter
logger.jetty.name = org.sparkproject.jetty
logger.jetty.level = warn
